delete  NonlinearResults/NonlinearEigen.out;
delete  NonlinearResults/NonlinearPeriods.out;
delete  NonlinearResults/disp1040.out;
delete  NonlinearResults/reac10.out;
delete  NonlinearResults/reac20.out;
delete  NonlinearResults/reac30.out;
delete  NonlinearResults/reac40.out;
delete  NonlinearResults/drift1.out;
delete  NonlinearResults/drift2.out;
delete  NonlinearResults/drift3.out;
delete  NonlinearResults/drift4.out;
delete  NonlinearResults/drift5.out;
delete  NonlinearResults/drift6.out;
delete  NonlinearResults/drift7.out;
delete  NonlinearResults/drift8.out;
delete  NonlinearResults/drift9.out;
delete  NonlinearResults/drift10.out;
delete NonlinearResults/NLCForce.out
delete NonlinearResults/NLBrForce.out
delete  NonlinearResults/PlasticCRotation.out;
delete  NonlinearResults/PlasticBrStrain.out;
